* configure.ac: Warn if GDL2 isn't found. 	* configure: Regenerate.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/gsweb/trunk@28213 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1757,6 +1757,9 @@ if test "$GDL2" = yes; then
 #define HAVE_GDL2 1
 _ACEOF
 
+else
+  { echo "$as_me:$LINENO: WARNING: Could not find GNUstep Database Library 2. Will assume a compatible library exists anyway." >&5
+echo "$as_me: WARNING: Could not find GNUstep Database Library 2. Will assume a compatible library exists anyway." >&2;}
 fi
 
 
