2003-02-01   Manuel Guesdon <mguesdon@orange-concept.com> 	* GSWeb/NSString+Trimming.m: 		o Replaced DataToHexString with -[NSData 		 hexadecimalRepresentation]. (David Ayers <d.ayers@inode.at>) 	* GSWeb/GSWHTMLURLValuesElement.m: 		o Replaced GSMD5 class with md5Digest of NSData category. 		 (David Ayers <d.ayers@inode.at>) 		o Replaced DataToHexString with -[NSData 		 hexadecimalRepresentation].  (David Ayers <d.ayers@inode.at>) 	* Examples/hello/GNUmakefile: 		o Use gsweb.make. 	* gsweb.make.in: 		o Change AUXILIARY_INCLUDE_LIBS to AUXILIARY_TOOL_LIB. 		 (David Ayers <d.ayers@inode.at>) 		o Handle GDL2 with ADDITIONAL_OBJCFLAGS. 		 (David Ayers <d.ayers@inode.at>) 	* configure.ac: 		o Check for GDL2 to set config.h correctly. 	* configure: 		o Regenerated. (David Ayers <d.ayers@inode.at>) 	* config.mak.in: 		o Set GDL2 as determined by configure. (David Ayers <d.ayers@inode.at>) 	* GSWeb.framework/GSWComponent.m: 		o use GSWApp -createResponseInContext: instead of creating 			GSWResponse instance directly 		o added -_appendPageToResponse:inContext: 	* GSWeb.framework/GSWApplication.[hm]: 		o added -createResponseInContext: 		o added -createRequestWithMethod:uri:httpVersion:headers:content:userInfo: 		o added -createResourceManager 		o used createResourceManager instead of creating it directly 		o added NSAutoreleasePool debug traces 		o exception log changed 	* GSWeb.framework/GSWDefaultAdaptorThread.m: 		o use application -createRequestWithMethod:uri:httpVersion:headers:content:userInfo: 			instead of directly creating GSWRequest instance directly 		o added NSAutoreleasePool debug traces 	 	o add thread_id trace in log 	* GSWeb.framework/GSWDefaultAdaptor.m: 		o added NSAutoreleasePool debug traces 	* GSWeb.framework/GSWComponentRequestHandler.m: 		o use GSWApp -createResponseInContext: instead of creating 			GSWResponse instance directly 	* GSWeb.framework/GSWResourceRequestHandler.m: 		o use GSWApp -createResponseInContext: instead of creating 			GSWResponse instance directly 	* GSWeb.framework/GSWDirectActionRequestHandler.m: 		o use GSWApp -createResponseInContext: instead of creating 			GSWResponse instance directly 	* GSWeb.framework/GSWResponse.m: 		o use GSWApp -createResponseInContext: instead of creating 			GSWResponse instance directly 	* GSWeb.framework/GSWTemplateParserXML.m: 		o added exception handling 		o added NSAutoreleasePool debug traces 	* GSWeb.framework/GSWTemplateParser.m: 		o added NSAutoreleasePool debug traces 	* GSWeb.framework/GSWSession.m 		o added NSAutoreleasePool debug traces 		o Fix in rand() use 		o NSString+Trimming 		o Fix in rand() use 	 	o add thread_id trace in log 		o Replaced GSMD5 class with md5Digest of NSData category. 		  (David Ayers <d.ayers@inode.at>) 		o Replaced DataToHexString with -[NSData 		hexadecimalRepresentation].  (David Ayers <d.ayers@inode.at>) 	* GSWeb.framework/GSWContext.m 		o add thread_id trace in log 	* GSWeb/GSWUtils.[hm]: 		o Removed DataToHexString() and HexStringToData(). 		  (David Ayers <d.ayers@inode.at>)
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/gsweb/trunk@15846 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1173,8 +1173,41 @@ fi
 echo "$as_me:$LINENO: result: $GSWNAMES" >&5
 echo "${ECHO_T}$GSWNAMES" >&6
 
+#--------------------------------------------------------------------
+# Check for GDL2
+#--------------------------------------------------------------------
+as_ac_File=`echo "ac_cv_file_$GNUSTEP_MAKEFILES/Auxiliary/gdl2.make" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $GNUSTEP_MAKEFILES/Auxiliary/gdl2.make" >&5
+echo $ECHO_N "checking for $GNUSTEP_MAKEFILES/Auxiliary/gdl2.make... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$GNUSTEP_MAKEFILES/Auxiliary/gdl2.make"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  GDL2=yes
+else
+  GDL2=no
+fi
 
+if test "$GDL2" = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GDL2 1
+_ACEOF
 
+fi
+
+ 
 #--------------------------------------------------------------------
 # Check for libwrap
 #--------------------------------------------------------------------
@@ -2874,6 +2907,7 @@ s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
 s,@GSWNAMES@,$GSWNAMES,;t t
+s,@GDL2@,$GDL2,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
